development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: geezeo_development
  pool:     5
  username: 
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: geezeo_test
  pool:     5
  username: 
  password:
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: geezeo_production
  pool:     5
  username: geezeo
  password:
  template: template0
